### ISSUE TITLE
User with `OML.can_manage_organization` and `Admin` in a meeting cannot see they created topics

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#317] opened 2021-09-10 09:27 UTC
As a user with the OML `OML.can_manage_organization` and as an `Admin` of a meeting, I created a topic in the meeting.
Afterwards I cannot see the topic and get no updates to related objects of that topic. 

See the picture:
![topic_missing-content-object](https://user-images.githubusercontent.com/10206688/132832455-44298284-c1c8-44e3-a89a-7663439512e9.png)

**Comment by ostcar** [comment] 2021-09-10 12:14
I can not reproduce this. I started with a new datastore. Then I created a new meeting and a new user with OML can manage organization and added him in the admin group of the new meeting. Then I created a new topic with this user. This worked fine. I don't get the image, that you posted.

Can you tell me step by step what you did? Can you also paste the body of the request to the autoupdate service? Are there any log messages of the autoupdate-service?

**Comment by GabrielInTheWorld** [comment] 2021-09-10 12:42
The steps I did, I have written in the description.

This is the request to the AU-service:
```json
[
  {
    "collection":"meeting",
    "ids":[
      3
    ],
    "fields":{
      "id":null,
      "agenda_item_ids":{
        "type":"relation-list",
        "collection":"agenda_item",
        "fields":{
          "item_number":null,
          "comment":null,
          "closed":null,
          "type":null,
          "is_hidden":null,
          "is_internal":null,
          "duration":null,
          "weight":null,
          "level":null,
          "parent_id":null,
          "child_ids":null,
          "meeting_id":null,
          "id":null,
          "content_object_id":{
            "type":"generic-relation",
            "fields":{
              "title":null,
              "number":null,
              "id":null,
              "agenda_item_id":null,
              "text":null,
              "list_of_speakers_id":{
                "type":"relation",
                "collection":"list_of_speakers",
                "fields":{
                  "closed":null,
                  "id":null,
                  "speaker_ids":{
                    "type":"relation-list",
                    "collection":"speaker",
                    "fields":{
                      "begin_time":null,
                      "end_time":null,
                      "id":null
                    }
                  }
                }
              },
              "submitter_ids":{
                "type":"relation-list",
                "collection":"motion_submitter",
                "fields":{
                  "user_id":{
                    "type":"relation",
                    "collection":"user",
                    "fields":{
                      "title":null,
                      "first_name":null,
                      "last_name":null,
                      "username":null,
                      "id":null
                    }
                  },
                  "weight":null,
                  "id":null
                }
              }
            }
          }
        }
      }
    }
  }
]
```

There are no log messages from the AU-service since it does not log anything...

**Comment by GabrielInTheWorld** [comment] 2021-09-10 12:44
As a user with the OML `OML.superadmin` I see the topic...

**Comment by ostcar** [comment] 2021-09-10 13:06
As I already wrote, I did exactly the same as you described in your description and I could not reproduce it. So either we used different code or different start date or did something different. Therefore I need a better description, step by step, what you did.

In other case, I can not help you

**Comment by GabrielInTheWorld** [comment] 2021-09-13 06:22
Well, it seems that it works fine in the demo. Then, I will inform you, if could find the reason, why the described behaviour happened.

**Comment by ostcar** [comment] 2021-09-20 19:39
@emanuelschuetze  can you confirm this issue? In other case I will close it.

**Comment by tsiegleauq** [comment] 2021-09-23 12:37
@emanuelschuetze and I just confirmed it.

**Comment by emanuelschuetze** [comment] 2021-09-23 12:40
reproduced with 8086d137bd78cfd7180aa5028d7ae49a8e69f924 (current main of autoupdate) by creating a topic item (in first tab) as orga admin and observing the agenda with a second tab (same admin).

**Comment by ostcar** [comment] 2021-09-25 11:05
I think I found the bug. Please confirm, that #326 fixes this issue.

For the future. Please write better bug reports. You only showed me an image from the client. But I don't know in which conditions the client uses the title "<missing content object>".

As I had to find out, this happens, if the autoupdate-service does not return the key agenda_item/content_object_id.

So for the future, please always tell me which request to send, which response you got and which response you expected. Please try to reduce the request. To reproduce the bug, it is not necessary to request 20 keys. So please remove as many keys from the request as possible.

**Closed** 2021-10-02 21:20 UTC
Labels: bug, autoupdate, high

**Comment by GabrielInTheWorld** [comment] 2021-10-04 06:36
> I think I found the bug. Please confirm, that #326 fixes this issue.
> 

First of all, do not just merge your PR, if you requested a review and at least one have to review a PR.
Your PR #326 seems to work.

> For the future. Please write better bug reports. You only showed me an image from the client. But I don't know in which conditions the client uses the title "".
> 

To write better bug reports, we need better logs or logs at all...

**Comment by ostcar** [comment] 2021-10-04 08:45
> > I think I found the bug. Please confirm, that #326 fixes this issue.
> > 
> 
> First of all, do not just merge your PR, if you requested a review and at least one have to review a PR.
> Your PR #326 seems to work.

I had this pr open for one week. After a week I will merge PRs even if you did not respond.

> > For the future. Please write better bug reports. You only showed me an image from the client. But I don't know in which conditions the client uses the title
> > 
> 
> To write better bug reports, we need better logs or logs at all...

I don't see why you need logs to tell me which request you send and what response was returned.

**Comment by GabrielInTheWorld** [comment] 2021-10-06 09:34
> I had this pr open for one week. After a week I will merge PRs even if you did not respond.
> 

This is a no go...

> 
> I don't see why you need logs to tell me which request you send and what response was returned.

Because logs are useful to debug the application
