### ISSUE TITLE
Loosen restrictions for motion_states

### ISSUE THREAD

**Issue by luisa-beerboom** [OpenSlides/openslides-autoupdate-service#599] opened 2022-12-15 13:38 UTC
Necessary for OpenSlides/openslides-client#620

The restrictions for `motion_state` need to be changed to also allow people who can see the origin motion of any motions which have that state.

Please cross-check whether this breaks anything in the client before merging though (The client-side restrictions may not be heavy enough to stop these models from being shown in the origin state overviews, between merging the solution for this and the client-side solution, we don't want to have a broken client in the meantime)

**Comment by jsangmeister** [comment] 2022-12-20 08:05
this will be done automatically once https://github.com/OpenSlides/openslides-backend/pull/1566 is merged

**Comment by luisa-beerboom** [comment] 2023-01-17 12:17
> this will be done automatically once [OpenSlides/openslides-backend#1566](https://github.com/OpenSlides/openslides-backend/pull/1566) is merged

No, this issue is meant to un-restrict states from other meetings so that the client can actually load them and display their data. They are currently restricted to only be visible to people who have motion_can_see in the same meeting. Even if the backend changes from OpenSlides/openslides-backend#1566 (which allow me to see the state_id but NOT the state) are merged, the client still wont be able to actually load the name and appearance of it (which would make this entire exercise pointless)!

**Comment by jsangmeister** [comment] 2023-01-19 09:00
Ah, I see. What exactly needs to be changed? What fields do you need? Do restriction modes need to be changed?

**Comment by luisa-beerboom** [comment] 2023-01-19 09:59
As I already mostly stated above: 
The restrictions in `motion_state.go` need to be changed in the following manner:
- If we have a meeting 'A':
   1. People with motion_can_see in meeting A should be able to see the entirety of every motion state of meeting A (this is already happening)
   2. If a motion has been forwarded to a meeting 'B', the state that is applied to said derived motion in meeting B should also be visible to People who have motion_can see in meeting A
- For the second condition I only really need the fields necessary for displaying the state-chip, so I think the fields `name`, `css_class`, and `show_state_extension_field` would be the bare minimum (the rest I would leave to the good judgement of whomever will be implementing this)
- If the check for the second condition is too complicated we can also just go by the criteria of "can my meeting/committee forward to that meeting" (I'm only subscribing to this as part of the detail subscription anyway)

**Comment by jsangmeister** [comment] 2023-01-19 10:37
So, to formalize, I would suggest the following changes to the `motion_state` restrictions in https://github.com/OpenSlides/openslides-autoupdate-service/blob/fa3ed9d8e15330a8b1f71f24a5a45807e13dac92/internal/restrict/collection/motion_state.go:
```
// The user can see a motion state if:
//     The user has motion.can_see, or
//     For one motion in motion_ids: The user can see a referenced motion in motion/all_origin_ids or motion/all_derived_motion_ids.
//
// Mode A: The user can see the motion state.
```
For ease of usage, I would just leave everything in the same restriction mode.

@luisa-beerboom does this fullfil your needs or did I miss anything?

@ostcar is this feasible? This runs in `O(n²*f(x))` where `f(x)` is the runtime of the check if the user can see a motion. I hope that's not too much, but I don't know of a faster way to check if a user may see a state of a foreign meeting.

**Comment by luisa-beerboom** [comment] 2023-01-19 10:55
@jsangmeister motion/all_derived_motion_ids wouldn't even have been necessary, but it is fine by me.

This will work for me

**Comment by jsangmeister** [comment] 2023-01-19 12:06
Ok, then we'll remove it. Saves restriction work and smaller restrictions are always better.

**Comment by jsangmeister** [comment] 2023-01-19 12:08
You mean `all_origin_ids`, right? If A forwards to B and a user looking at B wants to see the state of A, then (looking from the state) B is in `all_derived_motion_ids` of A.

**Comment by luisa-beerboom** [comment] 2023-01-19 12:29
If A forwards to B, then the person looking at the _origin motion_ (in A) should be able to see the state of the _derived motion_ (i.e. B).
Therefore we need `all_origin_ids`

**Comment by jsangmeister** [comment] 2023-01-19 13:17
Ah, okay! I thought it was the other way around. Updated accordingly.

**Comment by ostcar** [comment] 2023-01-19 13:39
I don't think the user has `to see` the other motion but has the restriction mode A of the other motion. See the difference between mode A and mode C from motions: https://github.com/OpenSlides/openslides-autoupdate-service/blob/fa3ed9d8e15330a8b1f71f24a5a45807e13dac92/internal/restrict/collection/motion.go#L13-L26

`motion/modeC` is `can see` but `motion/modeA` is for fields that require the origin_ids.

I don't think this change is expensive. The restriction uses a Cache (since last weekend). If the client requests the origin motion and the origin motion_state in the same request, then motion/modeA is calculated anyway.

How fast do you need this? Is it ok when we first finish the `feature/remove-template-fields` project? There would be merge conflicts.

**Comment by jsangmeister** [comment] 2023-01-19 13:57
> I don't think the user has `to see` the other motion but has the restriction mode A of the other motion.

I'm aware of the difference, but I think it is a formulation question: If M1 forwards to M2 and the user is looking at M1, he or she wants to see the state of M2. So, looking from the state of M2, M2 is in its `motion_ids` list and M1 is in the `all_origin_ids` list of M2. So, the user either needs to be able to see M1 or have restriction mode A for M2 - these two are equivalent. Implementation-wise, your approach is probably better because you can reuse more code, but formulation-wise I don't think it would be good to reference the restriction mode of the `motion` collection in the `motion_state` file.

> How fast do you need this? Is it ok when we first finish the `feature/remove-template-fields` project? There would be merge conflicts.

@luisa-beerboom

**Comment by luisa-beerboom** [comment] 2023-01-19 14:18
This is for an older feature issue, so it isn't that pressing. Given that I have already started implementing it in the client, I would prefer if it happens sooner rather than later, but if it is too much work we can postpone this.

**Comment by jsangmeister** [comment] 2023-01-19 14:32
Okay, as I said, the implementation can can differ from the formulation in the file as long as it does the same. I would like to keep my formulation as I think it's less confusing since it does not reference the motion's restriction modes, but after all, you will create the PR and write the description ;)

**Comment by ostcar** [comment] 2023-09-18 07:40
This issue was on hold until the rtf-branch was merged.

I can do it know. Can you give me a ping, if this issue is still accurate an should be done?

**Comment by luisa-beerboom** [comment] 2023-09-18 08:01
> This issue was on hold until the rtf-branch was merged.
> 
> I can do it know. Can you give me a ping, if this issue is still accurate an should be done?

If this is done, the client would have to be done in the same sprint. Therefore I think @rrenkert should prioritize this

**Comment by ostcar** [comment] 2024-03-03 07:34
@rrenkert Can you tell me, if this is still needed? The issue is more then a year old

**Comment by ostcar** [comment] 2024-05-11 10:47
I close this for now. Please reopen, if this change will be necessary again

**Closed by ostcar** 2024-05-11 10:47 UTC
Labels: feature, needs info
