### ISSUE TITLE
Projection error, maybe related to CLOS

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#211] opened 2021-05-17 09:36 UTC
When I project a user on both projectors of the example data, I get

```
Internal Error: get first time restricted data: get values for keys `[meeting/1/name meeting/1/start_time meeting/1/end_time meeting/1/id meeting/1/projector_ids meeting/1/description projector/2/header_background_color projector/2/scroll projector/1/current_projection_ids projector/2/current_projection_ids projector/2/show_title projector/2/name projector/1/used_as_reference_projector_meeting_id projector/2/used_as_reference_projector_meeting_id projector/2/show_clock projector/1/header_font_color projector/2/background_color projector/1/aspect_ratio_numerator projector/1/show_logo projector/1/header_h1_color projector/1/chyron_font_color projector/1/show_header_footer projector/2/color projector/1/width projector/1/scale projector/1/name projector/1/aspect_ratio_denominator projector/1/id projector/2/id projector/2/scale projector/2/aspect_ratio_numerator projector/2/header_h1_color projector/2/header_font_color projector/1/background_color projector/1/scroll projector/1/chyron_background_color projector/2/show_logo projector/2/aspect_ratio_denominator projector/2/chyron_background_color projector/1/color projector/1/show_title projector/2/chyron_font_color projector/2/show_header_footer projector/2/width projector/1/show_clock projector/1/header_background_color projection/3/id projection/5/weight projection/6/content projection/6/id projection/6/stable projection/6/content_object_id projection/3/content projection/3/stable projection/5/content projection/6/type projection/6/weight projection/3/content_object_id projection/5/content_object_id projection/5/type projection/3/type projection/5/id projection/5/stable projection/3/options projection/3/weight projection/6/options projection/5/options meeting/1/is_hidden meeting/1/running user/2/voted_ids user/2/id meeting/1/weight meeting/1/default_password user/2/comment user/2/running user/2/tag_ids meeting/1/recommendation_id meeting/1/is_physical_person user/2/is_physical_person user/2/votesvalid meeting/1/default_poll_description meeting/1/global_abstain meeting/1/is_present_in_meeting_ids user/2/global_yes user/2/entitled_group_ids user/2/pollmethod meeting/1/votesinvalid meeting/1/username meeting/1/comment_ids meeting/1/content_object_id meeting/1/level user/2/global_abstain user/2/default_number user/2/number user/2/is_present_in_meeting_ids user/2/countdown_time user/2/item_number meeting/1/structure_level_$ meeting/1/agenda_item_id user/2/comment_ids user/2/duration user/2/default_password meeting/1/poll_ids meeting/1/votesvalid meeting/1/category_id meeting/1/global_no meeting/1/email meeting/1/message user/2/filesize user/2/last_name user/2/child_ids meeting/1/about_me meeting/1/open_posts meeting/1/majority_method user/2/phase meeting/1/child_ids meeting/1/voted_ids user/2/vote_weight_$ user/2/sequential_number meeting/1/comment meeting/1/speaker_ids meeting/1/min_votes_amount user/2/is_hidden meeting/1/phase meeting/1/default_structure_level user/2/max_votes_amount meeting/1/mimetype user/2/default_structure_level user/2/majority_method user/2/candidate_ids meeting/1/state_extension meeting/1/global_option_id meeting/1/entitled_group_ids meeting/1/tag_ids meeting/1/parent_id meeting/1/description meeting/1/block_id user/2/title user/2/modified_final_version meeting/1/text meeting/1/option_ids meeting/1/recommendation_extension meeting/1/duration user/2/message user/2/internal meeting/1/closed meeting/1/is_directory user/2/speaker_ids user/2/global_option_id meeting/1/title meeting/1/max_votes_amount user/2/votesinvalid user/2/amendment_paragraph_$ meeting/1/state user/2/meeting_id meeting/1/filesize meeting/1/is_internal user/2/default_time user/2/first_name user/2/category_id user/2/is_directory user/2/closed user/2/text user/2/lead_motion_id user/2/structure_level_$ user/2/default_poll_description user/2/recommendation_id user/2/is_internal meeting/1/lead_motion_id user/2/description user/2/number_poll_candidates user/2/level user/2/global_no user/2/recommendation_extension meeting/1/item_number meeting/1/votescast meeting/1/number_poll_candidates meeting/1/global_yes user/2/reason user/2/number_$ user/2/weight meeting/1/personal_note_ids meeting/1/create_timestamp user/2/last_email_send user/2/gender meeting/1/default_vote_weight user/2/email user/2/default_vote_weight user/2/create_timestamp user/2/comment_$ meeting/1/amendment_paragraph_$ meeting/1/internal meeting/1/last_email_send meeting/1/default_number user/2/min_votes_amount user/2/poll_ids user/2/state meeting/1/pollmethod meeting/1/gender meeting/1/reason meeting/1/sequential_number meeting/1/meeting_id meeting/1/onehundred_percent_base user/2/parent_id meeting/1/candidate_ids meeting/1/number_$ meeting/1/countdown_time meeting/1/modified_final_version user/2/is_active user/2/personal_note_ids user/2/option_ids user/2/block_id user/2/onehundred_percent_base meeting/1/vote_weight_$ meeting/1/default_time user/2/mimetype meeting/1/id meeting/1/is_active meeting/1/number user/2/type meeting/1/type meeting/1/has_inherited_access_groups user/2/open_posts meeting/1/first_name meeting/1/comment_$ meeting/1/last_name user/2/votescast user/2/has_inherited_access_groups user/2/content_object_id user/2/about_me user/2/username user/2/state_extension user/2/agenda_item_id user/2/number_$1 user/2/structure_level_$1 user/2/comment_$1 user/2/vote_weight_$1]` from datastore: getOrSet for keys `[meeting/1/name meeting/1/start_time meeting/1/end_time meeting/1/id meeting/1/projector_ids meeting/1/description projector/2/header_background_color projector/2/scroll projector/1/current_projection_ids projector/2/current_projection_ids projector/2/show_title projector/2/name projector/1/used_as_reference_projector_meeting_id projector/2/used_as_reference_projector_meeting_id projector/2/show_clock projector/1/header_font_color projector/2/background_color projector/1/aspect_ratio_numerator projector/1/show_logo projector/1/header_h1_color projector/1/chyron_font_color projector/1/show_header_footer projector/2/color projector/1/width projector/1/scale projector/1/name projector/1/aspect_ratio_denominator projector/1/id projector/2/id projector/2/scale projector/2/aspect_ratio_numerator projector/2/header_h1_color projector/2/header_font_color projector/1/background_color projector/1/scroll projector/1/chyron_background_color projector/2/show_logo projector/2/aspect_ratio_denominator projector/2/chyron_background_color projector/1/color projector/1/show_title projector/2/chyron_font_color projector/2/show_header_footer projector/2/width projector/1/show_clock projector/1/header_background_color projection/3/id projection/5/weight projection/6/content projection/6/id projection/6/stable projection/6/content_object_id projection/3/content projection/3/stable projection/5/content projection/6/type projection/6/weight projection/3/content_object_id projection/5/content_object_id projection/5/type projection/3/type projection/5/id projection/5/stable projection/3/options projection/3/weight projection/6/options projection/5/options meeting/1/is_hidden meeting/1/running user/2/voted_ids user/2/id meeting/1/weight meeting/1/default_password user/2/comment user/2/running user/2/tag_ids meeting/1/recommendation_id meeting/1/is_physical_person user/2/is_physical_person user/2/votesvalid meeting/1/default_poll_description meeting/1/global_abstain meeting/1/is_present_in_meeting_ids user/2/global_yes user/2/entitled_group_ids user/2/pollmethod meeting/1/votesinvalid meeting/1/username meeting/1/comment_ids meeting/1/content_object_id meeting/1/level user/2/global_abstain user/2/default_number user/2/number user/2/is_present_in_meeting_ids user/2/countdown_time user/2/item_number meeting/1/structure_level_$ meeting/1/agenda_item_id user/2/comment_ids user/2/duration user/2/default_password meeting/1/poll_ids meeting/1/votesvalid meeting/1/category_id meeting/1/global_no meeting/1/email meeting/1/message user/2/filesize user/2/last_name user/2/child_ids meeting/1/about_me meeting/1/open_posts meeting/1/majority_method user/2/phase meeting/1/child_ids meeting/1/voted_ids user/2/vote_weight_$ user/2/sequential_number meeting/1/comment meeting/1/speaker_ids meeting/1/min_votes_amount user/2/is_hidden meeting/1/phase meeting/1/default_structure_level user/2/max_votes_amount meeting/1/mimetype user/2/default_structure_level user/2/majority_method user/2/candidate_ids meeting/1/state_extension meeting/1/global_option_id meeting/1/entitled_group_ids meeting/1/tag_ids meeting/1/parent_id meeting/1/description meeting/1/block_id user/2/title user/2/modified_final_version meeting/1/text meeting/1/option_ids meeting/1/recommendation_extension meeting/1/duration user/2/message user/2/internal meeting/1/closed meeting/1/is_directory user/2/speaker_ids user/2/global_option_id meeting/1/title meeting/1/max_votes_amount user/2/votesinvalid user/2/amendment_paragraph_$ meeting/1/state user/2/meeting_id meeting/1/filesize meeting/1/is_internal user/2/default_time user/2/first_name user/2/category_id user/2/is_directory user/2/closed user/2/text user/2/lead_motion_id user/2/structure_level_$ user/2/default_poll_description user/2/recommendation_id user/2/is_internal meeting/1/lead_motion_id user/2/description user/2/number_poll_candidates user/2/level user/2/global_no user/2/recommendation_extension meeting/1/item_number meeting/1/votescast meeting/1/number_poll_candidates meeting/1/global_yes user/2/reason user/2/number_$ user/2/weight meeting/1/personal_note_ids meeting/1/create_timestamp user/2/last_email_send user/2/gender meeting/1/default_vote_weight user/2/email user/2/default_vote_weight user/2/create_timestamp user/2/comment_$ meeting/1/amendment_paragraph_$ meeting/1/internal meeting/1/last_email_send meeting/1/default_number user/2/min_votes_amount user/2/poll_ids user/2/state meeting/1/pollmethod meeting/1/gender meeting/1/reason meeting/1/sequential_number meeting/1/meeting_id meeting/1/onehundred_percent_base user/2/parent_id meeting/1/candidate_ids meeting/1/number_$ meeting/1/countdown_time meeting/1/modified_final_version user/2/is_active user/2/personal_note_ids user/2/option_ids user/2/block_id user/2/onehundred_percent_base meeting/1/vote_weight_$ meeting/1/default_time user/2/mimetype meeting/1/id meeting/1/is_active meeting/1/number user/2/type meeting/1/type meeting/1/has_inherited_access_groups user/2/open_posts meeting/1/first_name meeting/1/comment_$ meeting/1/last_name user/2/votescast user/2/has_inherited_access_groups user/2/content_object_id user/2/about_me user/2/username user/2/state_extension user/2/agenda_item_id user/2/number_$1 user/2/structure_level_$1 user/2/comment_$1 user/2/vote_weight_$1]`: fetching key: fetching missing keys: calculating key projection/3/content: calculating slide: fetching user/2/list_of_speakers_id: user/2/list_of_speakers_id does not exist.
```

I suspect the CLOS slide to see an update of the first projector, where a user is projected, but a user does not have a `list_of_speakers_id`. This must be catched.

**Comment by ostcar** [comment] 2021-05-17 12:12
This is a duplicate of #201. Every time the error message ends with "does not exist in cache" this means, that there is some kind of invalid state in the cache. This has nothing to do with the projector code or some other parts of the autoupdate service.

**Closed by ostcar** 2021-05-17 12:12 UTC
Labels: autoupdate, bug, projector
