### ISSUE TITLE
Data formatting is wrong

### ISSUE THREAD

**Issue by FinnStutzenstein** [OpenSlides/openslides-autoupdate-service#68] opened 2020-06-19 06:45 UTC
The data should not contain any linebreaks (https://github.com/OpenSlides/OpenSlides/blob/openslides4-dev/docs/client-server-streaming-communication.txt), but integer arrays are returned with linebreakes. E.g.:
```
{"user/1/username":"admin","user/1/first_name":"","user/1/last_name":"Administrator","user/1/group_1_ids":[
        2
      ],"group/2/permissions":[],"user/1/title":""}
```
with this request:
```
[{"collection":"user","ids":[1],"fields":{"title":null,"username":null,"first_name":null,"last_name":null,"group_1_ids":{"type":"relation-list","collection":"group","fields":{"permissions":null}}}}]
```
on the well known example data. The issue is here: https://github.com/OpenSlides/openslides-autoupdate-service/blob/master/internal/http/http.go#L142
I guess you can just use the build-in json library instead? Note that values can be arbitrary json.

**Comment by ostcar** [comment] 2020-06-19 11:39
I don't think the problem is in the http.go file.

I can not reproduce the error. Could you tell me how to load the example data by fixing this issue?
https://github.com/OpenSlides/openslides-datastore-service/issues/62

**Comment by ostcar** [comment] 2020-06-19 14:28
I was able to load the example data but still can not reproduce the error. I used the request from this issue. I get the following response:
```
{"user/1/last_name":"Administrator","user/1/group_1_ids":[2],"user/1/title":"","user/1/username":"admin","user/1/first_name":"","group/2/permissions":[]}
```

Can you tell me exactly what you did?

**Comment by ostcar** [comment] 2020-06-22 18:59
@FinnStutzenstein can I close this?

**Closed** 2020-06-23 05:15 UTC
