### ISSUE TITLE
Get history information for deleted models

### ISSUE THREAD

**Issue by jsangmeister** [OpenSlides/openslides-autoupdate-service#586] opened 2022-11-21 11:17 UTC
When querying the `history_information` route for a deleted model with a `meeting_id` (like `motion` or `assignment`), the request fails with the following error:
```
{type: "not_exist", msg: "motion/5/meeting_id does not exist"}
```
For models without a `meeting_id` like `user`, this is not an issue.

To provide a fully functional history, all deleted models should be queryable for their history information.

**Comment by ostcar** [comment] 2023-02-13 09:27
This is a big difficult. My current datastore-system does not fetch deleted objects (since they are not needed for autoupdates).

Would it be possible to move the history information to a backend-presenter? The history information has nothing to do with the autoupdate-format or the autoupdate-restricter.

**Comment by r-peschke** [comment] 2023-02-15 08:04
IMO the autoupdate-service is the "READER" of OpenSlides. The presenter IMO should be a dying service, needed to get information outside of permission rules and with  complex search and "accumulative"-criteria.

**Comment by ostcar** [comment] 2023-02-15 16:45
@rrenkert any thoughts?

**Comment by rrenkert** [comment] 2023-02-16 09:22
I think its a mix of the previous opinions.
The autoupdate-service should not care about old (and for sure not deleted) data and only send data _changes_ that _currently_ happen (may be its less than the autoupdate-service currently does).
The presenter is a construction to build workarounds and should not grow and better be replaced in the future.
Raises the question who presents the history data.
If we think of OS4 as a service oriented architecture application, the conclusion would be to implement a service for the history information as we do to deliver search results, mediafiles and do the votes etc…

**Comment by ostcar** [comment] 2023-02-16 09:32
@rrenkert If you like, I can build a history service. A frist version, that only returns the histroy information should be easy and very quick.

For the moment, I would leave the actual histroy data in the autoupdate service, until we decide how the SQL-Version will look like.

**Comment by rrenkert** [comment] 2023-02-16 10:56
We should not do quick shots on this. As I can only see a PR in the backend requesting this feature that has no issue, is not fully clarified and its not clear where this feature request comes from and is 3 month old with the label "high", we now can spend some time on the design.

**Comment by ostcar** [comment] 2023-02-16 12:32
Ok. I close this issue here.

**Comment by ostcar** [comment] 2023-02-16 12:32
Ok. I unissign me. Please ping me when there is something to do

**Closed by ostcar** 2023-02-16 12:32 UTC
Labels: bug, needs discussion

**Comment by r-peschke** [comment] 2023-02-20 07:54
I saw the issue is closed, but to clarify: "Autoupdating" is not the only task of the autoupdate-service. A better name would be read-and-autoupdate-service. The autoupdate-functionality is just an addon on reading data and restrict them to be shown in the client. Additionally it could be instructed to keep the data "autoupdated".
The reading part of the autoupdate-service is only limited to "field-wise reading" because of the idea of a key-value store. Conceptually it could implement complex reading features and store the results as fields to be updated.
We should think about where we want to go!
On more: In the datastore-adapter used in the backend as database interface, the "deleted"-yeas/no is just a parameter in  all data-retrieving-methods, no need for history service .
