### ISSUE TITLE
Meeting admins should be able to see forwarded motions when `is_submitter` restriction is set

### ISSUE THREAD

**Issue by bastianjoel** [OpenSlides/openslides-autoupdate-service#625] opened 2023-02-14 13:31 UTC
As a meeting admin only part of a motion is sent to the client for forwarded motions if only the `is_submitter` restriction is set within the workflow. This makes no sense and results in the client not being able to display all the motion information. 

The original issue is https://github.com/OpenSlides/openslides-client/issues/1979

**Comment by ostcar** [comment] 2023-02-17 07:24
This is a duplicate of https://github.com/OpenSlides/openslides-client/issues/1979. If there is something to do in the autoupdate service to fix the issue, then please transfer the issue in the autoupdate repo.

**Closed by ostcar** 2023-02-17 07:24 UTC
Labels: enhancement
