### ISSUE TITLE
Provide a more descriptable error message

### ISSUE THREAD

**Issue by GabrielInTheWorld** [OpenSlides/openslides-autoupdate-service#193] opened 2021-04-14 06:02 UTC
The client sent the folllowing payload:
```json
[
  {
    "collection":"meeting",
    "ids":[
      1
    ],
    "fields":{
      "name":null,
      "description":null,
      "start_time":null,
      "end_time":null,
      "location":null,
      "conference_show":null,
      "conference_auto_connect":null,
      "conference_los_restriction":null,
      "conference_stream_url":null,
      "projector_countdown_warning_time":null,
      "projector_default_countdown_time":null,
      "url_name":null,
      "is_template":null,
      "enable_anonymous":null,
      "export_csv_separator":null,
      "export_csv_encoding":null,
      "export_pdf_pagenumber_alignment":null,
      "export_pdf_fontsize":null,
      "export_pdf_pagesize":null,
      "agenda_show_subtitles":null,
      "agenda_enable_numbering":null,
      "agenda_number_prefix":null,
      "agenda_numeral_system":null,
      "agenda_item_creation":null,
      "agenda_new_items_default_visibility":null,
      "agenda_show_internal_items_on_projector":null,
      "list_of_speakers_amount_last_on_projector":null,
      "list_of_speakers_amount_next_on_projector":null,
      "list_of_speakers_couple_countdown":null,
      "list_of_speakers_enable_point_of_order_speakers":null,
      "list_of_speakers_show_amount_of_speakers_on_slide":null,
      "list_of_speakers_present_users_only":null,
      "list_of_speakers_show_first_contribution":null,
      "list_of_speakers_initially_closed":null,
      "motions_default_workflow_id":null,
      "motions_default_amendment_workflow_id":null,
      "motions_default_statute_amendment_workflow_id":null,
      "motions_preamble":null,
      "motions_default_line_numbering":null,
      "motions_line_length":null,
      "motions_reason_required":null,
      "motions_enable_text_on_projector":null,
      "motions_enable_reason_on_projector":null,
      "motions_enable_recommendation_on_projector":null,
      "motions_show_referring_motions":null,
      "motions_enable_sidebox_on_projector":null,
      "motions_show_sequential_number":null,
      "motions_recommendations_by":null,
      "motions_statute_recommendations_by":null,
      "motions_recommendation_text_mode":null,
      "motions_default_sorting":null,
      "motions_number_type":null,
      "motions_number_min_digits":null,
      "motions_number_with_blank":null,
      "motions_statutes_enabled":null,
      "motions_amendments_enabled":null,
      "motions_amendments_in_main_list":null,
      "motions_amendments_of_amendments":null,
      "motions_amendments_prefix":null,
      "motions_amendments_text_mode":null,
      "motions_amendments_multiple_paragraphs":null,
      "motions_supporters_min_amount":null,
      "motion_poll_default_type":null,
      "motion_poll_default_100_percent_base":null,
      "motion_poll_default_majority_method":null,
      "motion_poll_default_group_ids":null,
      "motion_poll_ballot_paper_selection":null,
      "motion_poll_ballot_paper_number":null,
      "motions_export_title":null,
      "motions_export_preamble":null,
      "motions_export_submitter_recommendation":null,
      "motions_export_follow_recommendation":null,
      "assignment_poll_default_method":null,
      "assignment_poll_default_type":null,
      "assignment_poll_default_100_percent_base":null,
      "assignment_poll_default_majority_method":null,
      "assignment_poll_default_group_ids":null,
      "assignment_poll_add_candidates_to_list_of_speakers":null,
      "assignment_poll_sort_poll_result_by_votes":null,
      "assignment_poll_ballot_paper_selection":null,
      "assignment_poll_ballot_paper_number":null,
      "assignments_export_title":null,
      "assignments_export_preamble":null,
      "users_sort_by":null,
      "users_enable_presence_view":null,
      "users_allow_self_set_present":null,
      "users_enable_vote_weight":null,
      "users_pdf_welcometitle":null,
      "users_pdf_welcometext":null,
      "users_pdf_url":null,
      "users_pdf_wlan_ssid":null,
      "users_pdf_wlan_password":null,
      "users_pdf_wlan_encryption":null,
      "users_email_sender":null,
      "users_email_replyto":null,
      "users_email_subject":null,
      "users_email_body":null,
      "custom_translations":null,
      "id":null,
      "logo_$_id":{
        "type":"template"
      },
      "font_$_id":{
        "type":"template"
      },
      "reference_projector_id":null,
      "default_group_id":{
        "type":"relation",
        "collection":"group",
        "fields":{
          "name":null,
          "permissions":null,
          "admin_group_for_meeting_id":null,
          "default_group_for_meeting_id":null,
          "id":null
        }
      },
      "admin_group_id":{
        "type":"relation",
        "collection":"group",
        "fields":{
          "name":null,
          "permissions":null,
          "admin_group_for_meeting_id":null,
          "default_group_for_meeting_id":null,
          "id":null
        }
      },
      "projector_ids":{
        "type":"relation-list",
        "collection":"projector",
        "fields":{
          "scale":null,
          "scroll":null,
          "width":null,
          "aspect_ratio_numerator":null,
          "aspect_ratio_denominator":null,
          "color":null,
          "background_color":null,
          "header_background_color":null,
          "header_font_color":null,
          "header_h1_color":null,
          "chyron_background_color":null,
          "chyron_font_color":null,
          "show_header_footer":null,
          "show_title":null,
          "show_logo":null,
          "show_clock":null,
          "name":null,
          "used_as_reference_projector_meeting_id":null,
          "id":null,
          "current_projection_ids":{
            "type":"relation-list",
            "collection":"projection",
            "fields":{
              "stable":null,
              "type":null,
              "options":null,
              "weight":null,
              "id":null,
              "content_object_id":{
                "type":"generic-relation",
                "fields":{
                  "title":null,
                  "number":null,
                  "sequential_number":null,
                  "text":null,
                  "reason":null,
                  "recommendation_id":null,
                  "tag_ids":null,
                  "personal_note_ids":null,
                  "block_id":null,
                  "category_id":null,
                  "lead_motion_id":null,
                  "comment_ids":null,
                  "modified_final_version":null,
                  "state_extension":null,
                  "recommendation_extension":null,
                  "agenda_item_id":null,
                  "amendment_paragraph_$":null,
                  "poll_ids":null,
                  "id":null,
                  "is_directory":null,
                  "parent_id":null,
                  "child_ids":null,
                  "mimetype":null,
                  "filesize":null,
                  "create_timestamp":null,
                  "has_inherited_access_groups":null,
                  "closed":null,
                  "content_object_id":null,
                  "speaker_ids":null,
                  "internal":null,
                  "open_posts":null,
                  "phase":null,
                  "candidate_ids":null,
                  "description":null,
                  "default_poll_description":null,
                  "number_poll_candidates":null,
                  "item_number":null,
                  "comment":null,
                  "type":null,
                  "is_hidden":null,
                  "is_internal":null,
                  "duration":null,
                  "weight":null,
                  "level":null,
                  "meeting_id":null,
                  "username":null,
                  "first_name":null,
                  "last_name":null,
                  "email":null,
                  "gender":null,
                  "is_active":null,
                  "is_physical_person":null,
                  "is_present_in_meeting_ids":null,
                  "last_email_send":null,
                  "number_$":{
                    "type":"template"
                  },
                  "default_number":null,
                  "comment_$":{
                    "type":"template"
                  },
                  "default_structure_level":null,
                  "structure_level_$":{
                    "type":"template"
                  },
                  "default_vote_weight":null,
                  "vote_weight_$":{
                    "type":"template"
                  },
                  "about_me":null,
                  "default_password":null,
                  "entitled_group_ids":null,
                  "state":null,
                  "pollmethod":null,
                  "voted_ids":null,
                  "votescast":null,
                  "votesinvalid":null,
                  "votesvalid":null,
                  "option_ids":null,
                  "majority_method":null,
                  "onehundred_percent_base":null,
                  "global_option_id":null,
                  "global_yes":null,
                  "global_no":null,
                  "global_abstain":null,
                  "min_votes_amount":null,
                  "max_votes_amount":null,
                  "message":null,
                  "default_time":null,
                  "countdown_time":null,
                  "running":null
                }
              }
            }
          },
          "preview_projection_ids":{
            "type":"relation-list",
            "collection":"projection",
            "fields":{
              "stable":null,
              "type":null,
              "options":null,
              "weight":null,
              "id":null,
              "content_object_id":{
                "type":"generic-relation",
                "fields":{
                  "title":null,
                  "number":null,
                  "sequential_number":null,
                  "text":null,
                  "reason":null,
                  "recommendation_id":null,
                  "tag_ids":null,
                  "personal_note_ids":null,
                  "block_id":null,
                  "category_id":null,
                  "lead_motion_id":null,
                  "comment_ids":null,
                  "modified_final_version":null,
                  "state_extension":null,
                  "recommendation_extension":null,
                  "agenda_item_id":null,
                  "amendment_paragraph_$":null,
                  "poll_ids":null,
                  "id":null,
                  "is_directory":null,
                  "parent_id":null,
                  "child_ids":null,
                  "mimetype":null,
                  "filesize":null,
                  "create_timestamp":null,
                  "has_inherited_access_groups":null,
                  "closed":null,
                  "content_object_id":null,
                  "speaker_ids":null,
                  "internal":null,
                  "open_posts":null,
                  "phase":null,
                  "candidate_ids":null,
                  "description":null,
                  "default_poll_description":null,
                  "number_poll_candidates":null,
                  "item_number":null,
                  "comment":null,
                  "type":null,
                  "is_hidden":null,
                  "is_internal":null,
                  "duration":null,
                  "weight":null,
                  "level":null,
                  "meeting_id":null,
                  "username":null,
                  "first_name":null,
                  "last_name":null,
                  "email":null,
                  "gender":null,
                  "is_active":null,
                  "is_physical_person":null,
                  "is_present_in_meeting_ids":null,
                  "last_email_send":null,
                  "number_$":{
                    "type":"template"
                  },
                  "default_number":null,
                  "comment_$":{
                    "type":"template"
                  },
                  "default_structure_level":null,
                  "structure_level_$":{
                    "type":"template"
                  },
                  "default_vote_weight":null,
                  "vote_weight_$":{
                    "type":"template"
                  },
                  "about_me":null,
                  "default_password":null,
                  "entitled_group_ids":null,
                  "state":null,
                  "pollmethod":null,
                  "voted_ids":null,
                  "votescast":null,
                  "votesinvalid":null,
                  "votesvalid":null,
                  "option_ids":null,
                  "majority_method":null,
                  "onehundred_percent_base":null,
                  "global_option_id":null,
                  "global_yes":null,
                  "global_no":null,
                  "global_abstain":null,
                  "min_votes_amount":null,
                  "max_votes_amount":null,
                  "message":null,
                  "default_time":null,
                  "countdown_time":null,
                  "running":null
                }
              }
            }
          }
        }
      },
      "poll_ids":{
        "type":"relation-list",
        "collection":"poll",
        "fields":{
          "entitled_group_ids":null,
          "state":null,
          "title":null,
          "type":null,
          "pollmethod":null,
          "content_object_id":{
            "type":"generic-relation",
            "fields":{
              "title":null,
              "number":null,
              "sequential_number":null,
              "text":null,
              "reason":null,
              "recommendation_id":null,
              "tag_ids":null,
              "personal_note_ids":null,
              "block_id":null,
              "category_id":null,
              "lead_motion_id":null,
              "comment_ids":null,
              "modified_final_version":null,
              "state_extension":null,
              "recommendation_extension":null,
              "agenda_item_id":null,
              "amendment_paragraph_$":null,
              "poll_ids":null,
              "id":null,
              "open_posts":null,
              "phase":null,
              "candidate_ids":null,
              "description":null,
              "default_poll_description":null,
              "number_poll_candidates":null
            }
          },
          "id":null
        }
      }
    }
  }
]
```

As a response, the autoupdate-service sent:
```json
{"error": {"type": "InternalError", "msg": "Ups, something went wrong!"}}
```

Provide a more descriptable error message, since it is not clear, why it goes wrong.

This happens, when I sign in with user "a".

**Comment by ostcar** [comment] 2021-04-14 07:18
The error message for the client is not informative by design. Please look at the error message in the server logs.

When the client gets the error message, there is always a log message.

**Comment by GabrielInTheWorld** [comment] 2021-04-14 07:46
I've seen this in the logs:
```
autoupdate_1        | 2021/04/14 07:44:33 Internal Error: get first time restricted data: restrict data: checker for key meeting/1/option_ids: check fqids: restrict for collection option: get permissions for poll 6: getting poll id: option/6/poll_id does not exist.
proxy_1             | {"level":"error","ts":1618386273.5934458,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"context canceled"}
autoupdate_1        | 2021/04/14 07:44:37 Internal Error: get first time restricted data: restrict data: checker for key meeting/1/option_ids: check fqids: restrict for collection option: get permissions for poll 6: getting poll id: option/6/poll_id does not exist.
```

Why tries the autoupdate-service to check `option/6/poll_id`?

**Comment by ostcar** [comment] 2021-04-14 08:00
The bug in not in the autoupdate service but in the permission service.

I don't know why the permission service needs the option. I have to check and fix it.

A workaround is, that you create the option to make the permission service happy. Or you can disable the permission service. DEACTIVATE_PERMISSION=true ( see readme)

**Comment by ostcar** [comment] 2021-04-16 08:25
Could you check that you are using the current master of the autoupdate service? If not, please update the autoupdate service and test this again. Please always make sure to use the newest version of the **autoupdate**-service before creating an issue. It is possible, that the main-repo references an old version of the autoupdate-service.

I can not reproduce the error. Your request works with the example data. Could to tell me how you changed the example data so I can test it on the same data than you?

The best way you can tell me how you changed the example data is with a data-object like this one:
```
{"topic/10/meeting_id": 1, "topic/10/title": "ZZ", "topic/10/text": ""}
```
It is a json-object where the key is a fqfield and the value is the new value as json.

Without reproducing it, I am not sure, if this is a bug. You requested `meeting/1/projector_ids/current_projection_ids/content_object_id/option_ids`.  The content of `option_ids` is a list of `int` representing the ids of options. The user should only get the option_ids from the options, which the user is allowed to see. Therefore the permission of each option is checked. To check the permission for an option, it is required that the option-object has the field [poll_id](https://github.com/OpenSlides/OpenSlides/blob/d216e3121ffb8909657b2031dfe4562bd3bacae0/docs/models.yml#L1792).

It seems in your data, there is an object on the projector, that has the field `option_ids` and with this field, it references `option/6`. This object `option/6` does not seem to have the required field `poll_id`. Could you check that?

To help you farther, than I need your database in the format I described above.

**Comment by GabrielInTheWorld** [comment] 2021-04-16 09:23
I have the current master branches of the auth-service, the datastore-service, the autoupdate-service, the backend and the permission-service.

- auth-service: edfb247a2398ae69dd5c0ff44e7cdf692b7c1b80
- autoupdate-service: d1a51b9bfecb8880b85044f58613946414492d02
- backend: 3e449bc4a9987e35ebe366ec2790d88f5cc6dd05
- datastore-service: 49abad2adadcfd09c3467a0f0b9f581a127f1258
- manage-service: a40e5bd940c41a1eb98533a01f046c0061e2d866
- permission-service: 26f9fece39bf18933b3d9a838e323182542549aa


Then, I have cleaned up my database (with `make stop-dev`) and rerun (with `make run-dev`).
I signed in with the default user `a`.
I can use OpenSlides until I reload my whole page (with `F5`).

A problem is still there. This time the autoupdate-service shows these logs:
```
autoupdate_1        | 2021/04/16 09:13:17 Internal Error: getting keys: get all keys: create keys for keysbuilder: load needed keys: restrict data: checker for key user/2/group_$1_ids: check fqids: restrict for collection group: checking group/6/id: getting meetingID from model group/6: getting meeting id: group/6/meeting_id does not exist.
autoupdate_1        | 2021/04/16 09:13:19 Internal Error: getting keys: get all keys: create keys for keysbuilder: load needed keys: restrict data: checker for key user/2/group_$1_ids: check fqids: restrict for collection group: checking group/6/id: getting meetingID from model group/6: getting meeting id: group/6/meeting_id does not exist.
```

**Comment by ostcar** [comment] 2021-04-16 09:47
@GabrielInTheWorld If I understand your last message correctly, then you can not reproduce your original error on the current master. If this is correct, than please close this issue.

I think that the problem of you new error is, that the current example-data are invalid. 

[user/2/group_$1_ids](https://github.com/OpenSlides/OpenSlides/blob/d216e3121ffb8909657b2031dfe4562bd3bacae0/docs/example-data.json#L119) contains the (group) id `6`. But there is no group with ID `6`: https://github.com/OpenSlides/OpenSlides/blob/d216e3121ffb8909657b2031dfe4562bd3bacae0/docs/example-data.json#L439

@FinnStutzenstein @normanjaeckel Maybe we need a way to validate the example data? But this issue is not the place to discuss this.
U

**Comment by GabrielInTheWorld** [comment] 2021-04-16 09:54
> @GabrielInTheWorld If I understand your last message correctly, then you can not reproduce your original error on the current master. If this is correct, than please close this issue.

No! It is the same error but with another relation!

**Comment by ostcar** [comment] 2021-04-16 09:59
It is not a bug to get a 500er, if the datastore contains invalid data. There is no valid response for invalid data.

I think, that your original request was fixed with this commit: https://github.com/OpenSlides/openslides-permission-service/commit/e30d357684526c139a397e11ed77ab5befcf2598

I understand your last command, that you do not get the old error for your original request. Therefore I close this issue. If you still get the error for the request in your first comment, than please reopen this issue and tell me that data you are using.

**Closed by ostcar** 2021-04-16 09:59 UTC
Labels: autoupdate, blocker, bug, high, needs info
